# Generated by Django 6.0.3 on 2026-04-26 19:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_chatmessage'),
        ('pharmacie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('sender_role', models.CharField(choices=[('pharmacist', 'Pharmacien'), ('customer', 'Patient'), ('doctor', 'Médecin'), ('admin', 'Administrateur')], max_length=20)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='pharmacie/chat/')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message de chat pharmacie',
                'verbose_name_plural': 'Messages de chat pharmacie',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_stock', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_stock', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('composition', models.TextField(blank=True)),
                ('dosage_form', models.CharField(blank=True, max_length=50)),
                ('strength', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('in_stock', 'En stock'), ('low_stock', 'Stock faible'), ('out_of_stock', 'Épuisé'), ('expired', 'Périmé')], default='in_stock', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('retrait', 'Retrait en pharmacie'), ('livraison', 'Livraison à domicile')], default='retrait', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En préparation'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('delivered', 'Livrée')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Non payé'), ('partial', 'Partiel'), ('paid', 'Payé')], default='unpaid', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('pharmacist_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('prescription_notes', models.TextField(blank=True)),
                ('dosage_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pharmacie',
                'verbose_name_plural': 'Pharmacies',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('adjustment', 'Ajustement'), ('return', 'Retour'), ('expired', 'Péremption')], max_length=20)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_time', '-created_at'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='pharmaciemessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Message Pharmacie', 'verbose_name_plural': 'Messages Pharmacie'},
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pharmaciemessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='pharmacie/chat_attachments/'),
        ),
        migrations.AddField(
            model_name='pharmaciemessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmaciemessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_conversations', to='doctor.consultation'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_conversations', to='doctor.patient'),
        ),
        migrations.AlterField(
            model_name='pharmaciemessage',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_chat_messages', to='doctor.consultation'),
        ),
        migrations.AlterField(
            model_name='pharmaciemessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pharmaciemessage',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_conversation_messages', to='doctor.patient'),
        ),
        migrations.AlterField(
            model_name='pharmaciemessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pharmacy_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pharmaciemessage',
            name='sender_role',
            field=models.CharField(choices=[('pharmacist', 'Pharmacien'), ('customer', 'Patient'), ('doctor', 'Médecin'), ('admin', 'Administrateur')], default='pharmacist', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pharmaciemessage',
            index=models.Index(fields=['conversation', '-created_at'], name='pharmacie_p_convers_ff38cf_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmaciemessage',
            index=models.Index(fields=['sender', '-created_at'], name='pharmacie_p_sender__05a080_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmaciemessage',
            index=models.Index(fields=['is_read', 'created_at'], name='pharmacie_p_is_read_f102b3_idx'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_messages', to='doctor.consultation'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_chat_messages', to='doctor.patient'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='pharmacie.category'),
        ),
        migrations.AddField(
            model_name='order',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_orders', to='doctor.consultation'),
        ),
        migrations.AddField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_orders', to='doctor.patient'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='pharmacie.medicine'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacie.order'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role__in': ['admin', 'pharmacie']}, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pharmacie.pharmacy'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacie.pharmacy'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='pharmacie.pharmacy'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='pharmacie.pharmacy'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('pharmacy', 'patient', 'consultation')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['pharmacy', '-last_message_time'], name='pharmacie_c_pharmac_189e63_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['patient', 'is_active'], name='pharmacie_c_patient_baf43c_idx'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.consultation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='pharmacie.medicine'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='pharmacie.order'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='pharmacie.pharmacy'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='pharmacie_o_order_n_02b58f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='pharmacie_o_status_3512a8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['patient', 'status'], name='pharmacie_o_patient_67d699_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['code'], name='pharmacie_m_code_b1eba6_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['status'], name='pharmacie_m_status_1fcf26_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['pharmacy', 'status'], name='pharmacie_m_pharmac_8d698a_idx'),
        ),
    ]
