# Generated by Django 6.0.3 on 2026-04-05 15:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('code_acte', models.CharField(max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'actes_medicaux',
            },
        ),
        migrations.CreateModel(
            name='CategorieProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'categories_produit',
            },
        ),
        migrations.CreateModel(
            name='MembreFamilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('lien_parente', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('frere', 'Frère'), ('soeur', 'Sœur'), ('fils', 'Fils'), ('fille', 'Fille'), ('epoux', 'Époux'), ('epouse', 'Épouse'), ('tuteur', 'Tuteur'), ('autre', 'Autre')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format : +228 XX XX XX XX', regex='^\\+228\\s?\\d{2}\\s?\\d{2}\\s?\\d{2}\\s?\\d{2}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membre Familial',
                'verbose_name_plural': 'Membres Familiaux',
                'db_table': 'membres_familiaux',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('doctor', 'Médecin'), ('patient', 'Patient')], default='patient', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format : +228 XX XX XX XX', regex='^\\+228\\s?\\d{2}\\s?\\d{2}\\s?\\d{2}\\s?\\d{2}$')])),
                ('specialty', models.CharField(blank=True, help_text='Spécialité du médecin : ophtalmo, chirurgie, urologie, cardiologie, general', max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text="Compte activé par l'admin")),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.CharField(choices=[('ophtalmo', 'Ophtalmologie'), ('chirurgie', 'Chirurgie'), ('urologie', 'Urologie'), ('cardiologie', 'Cardiologie'), ('general', 'Médecine Générale')], max_length=100)),
                ('centre_medical', models.CharField(max_length=150)),
                ('nom_soignant', models.CharField(max_length=100)),
                ('tel_soignant', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format : +228 XX XX XX XX', regex='^\\+228\\s?\\d{2}\\s?\\d{2}\\s?\\d{2}\\s?\\d{2}$')])),
                ('motif_consultation', models.TextField()),
                ('histoire_maladie', models.TextField(blank=True)),
                ('signes_fonctionnels', models.TextField(blank=True)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('ta_bras_gauche', models.CharField(blank=True, max_length=10)),
                ('ta_bras_droit', models.CharField(blank=True, max_length=10)),
                ('pouls', models.IntegerField(blank=True, null=True)),
                ('examen_physique', models.TextField(blank=True)),
                ('observations_cliniques', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'db_table': 'consultations',
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='AnalyseRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_radio', models.CharField(max_length=150)),
                ('type_analyse', models.CharField(max_length=200)),
                ('region_a_examiner', models.CharField(max_length=200)),
                ('motif', models.TextField()),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_radio', to='doctor.consultation')),
            ],
            options={
                'db_table': 'analyses_radio',
            },
        ),
        migrations.CreateModel(
            name='AnalyseLabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_labo', models.CharField(max_length=150)),
                ('analyses_demandees', models.TextField()),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_labo', to='doctor.consultation')),
            ],
            options={
                'db_table': 'analyses_labo',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('specialty', models.CharField(choices=[('ophtalmo', '👁️ Ophtalmologie'), ('chirurgie', '🔪 Chirurgie'), ('urologie', '🧪 Urologie'), ('cardiologie', '❤️ Cardiologie'), ('general', '🩺 Médecine Générale')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Médecin',
                'verbose_name_plural': 'Profils Médecins',
                'db_table': 'doctor_profiles',
            },
        ),
        migrations.CreateModel(
            name='ExamenCardiologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabete', models.BooleanField(default=False)),
                ('hta', models.BooleanField(default=False)),
                ('dyslipidemie', models.BooleanField(default=False)),
                ('heredite_cardio', models.BooleanField(default=False)),
                ('obesite', models.BooleanField(default=False)),
                ('sedentarite', models.BooleanField(default=False)),
                ('auscultation_cardiaque', models.TextField(blank=True)),
                ('palpation_pouls_peripheriques', models.TextField(blank=True)),
                ('oedemes_membres_inferieurs', models.BooleanField(default=False)),
                ('signes_insuffisance_cardiaque', models.TextField(blank=True)),
                ('electrocardiogramme_ecg', models.TextField(blank=True)),
                ('echocardiographie', models.TextField(blank=True)),
                ('holter_tensionnel_mapa', models.TextField(blank=True)),
                ('epreuve_effort', models.TextField(blank=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardiologie_details', to='doctor.consultation')),
            ],
            options={
                'db_table': 'examen_cardiologie',
            },
        ),
        migrations.CreateModel(
            name='ExamenOphtalmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('av_od_loin', models.CharField(blank=True, max_length=20)),
                ('av_og_loin', models.CharField(blank=True, max_length=20)),
                ('av_od_pres', models.CharField(blank=True, max_length=20)),
                ('av_og_pres', models.CharField(blank=True, max_length=20)),
                ('paupieres_annexes', models.TextField(blank=True)),
                ('conjonctive', models.TextField(blank=True)),
                ('cornee', models.TextField(blank=True)),
                ('chambre_anterieure', models.TextField(blank=True)),
                ('iris_pupille', models.TextField(blank=True)),
                ('cristallin', models.TextField(blank=True)),
                ('pression_intraoculaire_od', models.CharField(blank=True, max_length=20)),
                ('pression_intraoculaire_og', models.CharField(blank=True, max_length=20)),
                ('fond_oeil_od', models.TextField(blank=True)),
                ('fond_oeil_og', models.TextField(blank=True)),
                ('refraction_auto', models.TextField(blank=True)),
                ('correction_proposee', models.TextField(blank=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ophtalmo_details', to='doctor.consultation')),
            ],
            options={
                'db_table': 'examen_ophtalmo',
            },
        ),
        migrations.CreateModel(
            name='ExamenUrologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dysurie', models.BooleanField(default=False)),
                ('pollakiurie', models.BooleanField(default=False)),
                ('brulures_mictionnelles', models.BooleanField(default=False)),
                ('hematurie', models.BooleanField(default=False)),
                ('incontinence', models.BooleanField(default=False)),
                ('jet_faible', models.BooleanField(default=False)),
                ('examen_reins', models.TextField(blank=True)),
                ('examen_vessie', models.TextField(blank=True)),
                ('toucher_rectal', models.TextField(blank=True)),
                ('examen_organes_genitaux_externes', models.TextField(blank=True)),
                ('score_ipss', models.IntegerField(blank=True, null=True)),
                ('residu_post_mictionnel', models.CharField(blank=True, max_length=100)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urologie_details', to='doctor.consultation')),
            ],
            options={
                'db_table': 'examen_urologie',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_assurance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_patient', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut_paiement', models.CharField(choices=[('Non payé', 'Non payé'), ('Partiel', 'Partiel'), ('Payé', 'Payé')], default='Non payé', max_length=20)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture', to='doctor.consultation')),
            ],
            options={
                'db_table': 'factures',
            },
        ),
        migrations.CreateModel(
            name='InterventionChirurgicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(max_length=255)),
                ('indication_operatoire', models.TextField()),
                ('date_intervention', models.DateTimeField()),
                ('chirurgien_principal', models.CharField(max_length=100)),
                ('aide_chirurgien', models.CharField(blank=True, max_length=100)),
                ('type_anesthesie', models.CharField(max_length=100)),
                ('protocole_operatoire', models.TextField()),
                ('incidents_accidents', models.TextField(blank=True)),
                ('traitement_post_op', models.TextField()),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chirurgie_details', to='doctor.consultation')),
            ],
            options={
                'db_table': 'intervention_chirurgicale',
            },
        ),
        migrations.CreateModel(
            name='LigneFactureActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor.actemedical')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_actes', to='doctor.facture')),
            ],
            options={
                'db_table': 'lignes_facture_acte',
            },
        ),
        migrations.CreateModel(
            name='EntreeCarnetMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_service', models.CharField(choices=[('consultation', 'Consultation'), ('urgence', 'Urgence'), ('hospitalisation', 'Hospitalisation'), ('chirurgie', 'Chirurgie'), ('analyse', 'Analyse'), ('vaccination', 'Vaccination'), ('suivi', 'Suivi médical'), ('autre', 'Autre')], max_length=30)),
                ('medecin', models.CharField(max_length=150)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('traitement', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membre_familial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees_carnet', to='doctor.membrefamilial')),
            ],
            options={
                'verbose_name': 'Entrée Carnet Médical',
                'verbose_name_plural': 'Entrées Carnet Médical',
                'db_table': 'entrees_carnet_medical',
            },
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='doctor.consultation')),
            ],
            options={
                'db_table': 'ordonnances',
            },
        ),
        migrations.CreateModel(
            name='MedicamentPrescrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('posologie', models.CharField(max_length=200)),
                ('quantite', models.CharField(max_length=50)),
                ('duree', models.CharField(max_length=50)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='doctor.ordonnance')),
            ],
            options={
                'db_table': 'medicaments_prescrits',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('montant_verse', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('Espèces', 'Espèces'), ('Mobile Money', 'Mobile Money'), ('Carte Bancaire', 'Carte Bancaire'), ('Chèque', 'Chèque'), ('Assurance', 'Assurance')], max_length=50)),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='doctor.facture')),
            ],
            options={
                'db_table': 'paiements',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_patient', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format : +228 XX XX XX XX', regex='^\\+228\\s?\\d{2}\\s?\\d{2}\\s?\\d{2}\\s?\\d{2}$')])),
                ('adresse', models.TextField()),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('est_assure', models.BooleanField(default=False)),
                ('contact_urgence_nom', models.CharField(max_length=100)),
                ('contact_urgence_tel', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format : +228 XX XX XX XX', regex='^\\+228\\s?\\d{2}\\s?\\d{2}\\s?\\d{2}\\s?\\d{2}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='membrefamilial',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_familiaux', to='doctor.patient'),
        ),
        migrations.AddField(
            model_name='facture',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='doctor.patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='doctor.patient'),
        ),
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico_chirurgicaux', models.TextField(blank=True)),
                ('familiaux', models.TextField(blank=True)),
                ('tabac', models.BooleanField(default=False)),
                ('alcool', models.BooleanField(default=False)),
                ('activite_physique', models.CharField(blank=True, max_length=100)),
                ('autres_habitudes', models.TextField(blank=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents', to='doctor.patient')),
            ],
            options={
                'verbose_name': 'Antécédent',
                'verbose_name_plural': 'Antécédents',
                'db_table': 'antecedents',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_produit', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=255)),
                ('forme_galenique', models.CharField(blank=True, max_length=100)),
                ('prix_unitaire_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actuel', models.IntegerField(default=0)),
                ('stock_alerte', models.IntegerField(default=5)),
                ('date_peremption', models.DateField()),
                ('emplacement', models.CharField(blank=True, max_length=100)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='doctor.categorieproduit')),
            ],
            options={
                'db_table': 'produits',
            },
        ),
        migrations.CreateModel(
            name='LigneFacturePharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_pharmacie', to='doctor.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor.produit')),
            ],
            options={
                'db_table': 'lignes_facture_pharmacie',
            },
        ),
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_recue', models.IntegerField()),
                ('fournisseur', models.CharField(blank=True, max_length=150)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('numero_lot', models.CharField(blank=True, max_length=100)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvisionnements', to='doctor.produit')),
            ],
            options={
                'db_table': 'approvisionnements',
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut_paiement', models.CharField(choices=[('Payé', 'Payé'), ('En attente', 'En attente'), ('Annulé', 'Annulé')], default='Payé', max_length=20)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='doctor.patient')),
            ],
            options={
                'db_table': 'ventes',
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire_moment_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='doctor.vente')),
            ],
            options={
                'db_table': 'lignes_vente',
            },
        ),
    ]
