# Generated by Django 6.0.3 on 2026-04-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='service',
            field=models.CharField(choices=[('ophtalmo', 'Ophtalmologie'), ('chirurgie', 'Chirurgie'), ('urologie', 'Urologie'), ('cardio', 'Cardiologie'), ('general', 'Médecine Générale')], max_length=100),
        ),
    ]
